In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('wikipedia_dataset.xlsx')
data

,Page,2016-01-01 00:00:00,2016-01-02 00:00:00,2016-01-03 00:00:00,2016-01-04 00:00:00,2016-01-05 00:00:00,2016-01-06 00:00:00,2016-01-07 00:00:00,2016-01-08 00:00:00,2016-01-09 00:00:00,...,2016-12-22 00:00:00,2016-12-23 00:00:00,2016-12-24 00:00:00,2016-12-25 00:00:00,2016-12-26 00:00:00,2016-12-27 00:00:00,2016-12-28 00:00:00,2016-12-29 00:00:00,2016-12-30 00:00:00,2016-12-31 00:00:00
0,.xxx_en.wikipedia.org_all-access_all-agents,7089,7592,7436,7032,6498,6887,7209,7022,7194,...,4931.0,4034.0,5204.0,4331.0,4572.0,4509.0,5392.0,4950.0,2931.0,4101.0
1,.xxx_en.wikipedia.org_mobile-web_all-agents,6182,6447,6437,5912,5205,5770,5998,5948,6165,...,4617.0,3663.0,4882.0,4028.0,4263.0,4176.0,5068.0,4539.0,2666.0,3754.0
2,1._Juli_de.wikipedia.org_desktop_all-agents,20,49,33,49,34,26,66,28,18,...,26.0,20.0,19.0,43.0,24.0,41.0,39.0,39.0,31.0,31.0
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,5363,6280,6297,6288,6052,6200,5935,5958,6200,...,3356.0,3366.0,2912.0,2850.0,3140.0,3379.0,3497.0,3338.0,3329.0,3550.0
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,3186,3784,3832,4059,4022,4213,3985,3823,3794,...,1719.0,1593.0,1255.0,1160.0,1311.0,1468.0,1728.0,1494.0,1515.0,1464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,Zac_Efron_en.wikipedia.org_all-access_all-agents,14396,15501,13176,11001,13986,12006,9699,11266,11487,...,8195.0,8492.0,10283.0,8963.0,10900.0,12011.0,11575.0,11421.0,11847.0,13146.0
1496,Zayn_Malik_en.wikipedia.org_all-access_all-agents,31663,18883,19065,17978,16868,19067,23280,22064,17320,...,14947.0,15615.0,14232.0,12129.0,12919.0,13204.0,13095.0,12579.0,13094.0,12597.0
1497,Zendaya_en.wikipedia.org_all-access_all-agents,7091,6062,4719,4303,6027,5039,4182,4790,4981,...,7005.0,10630.0,8741.0,8623.0,7357.0,7540.0,8374.0,7262.0,7778.0,6217.0
1498,Zendaya_en.wikipedia.org_mobile-web_all-agents,5221,4344,3272,2757,4022,3065,2514,3060,3314,...,4707.0,8155.0,6941.0,6305.0,5493.0,5465.0,6100.0,5044.0,5752.0,4650.0
1499,Zodiac_Killer_en.wikipedia.org_all-access_all-...,4251,5850,5833,5732,5274,12615,6283,5537,4882,...,6054.0,6073.0,5448.0,6443.0,6913.0,7094.0,6921.0,8396.0,8275.0,6659.0

In [4]:
wiki_1 = pd.melt(data, id_vars='Page', 
                  var_name= 'Dates',
                  value_name= 'Daily_Page_Visit_Count'
                  )
wiki_1

,Page,Dates,Daily_Page_Visit_Count
0,.xxx_en.wikipedia.org_all-access_all-agents,2016-01-01,7089.0
1,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-01-01,6182.0
2,1._Juli_de.wikipedia.org_desktop_all-agents,2016-01-01,20.0
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-01-01,5363.0
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-01-01,3186.0
...,...,...,...
548995,Zac_Efron_en.wikipedia.org_all-access_all-agents,2016-12-31,13146.0
548996,Zayn_Malik_en.wikipedia.org_all-access_all-agents,2016-12-31,12597.0
548997,Zendaya_en.wikipedia.org_all-access_all-agents,2016-12-31,6217.0
548998,Zendaya_en.wikipedia.org_mobile-web_all-agents,2016-12-31,4650.0
548999,Zodiac_Killer_en.wikipedia.org_all-access_all-...,2016-12-31,6659.0

In [9]:
wiki_2 = wiki_1.rename(columns = {'Page' : 'Search_Topics'})
wiki_2.head()

,Search_Topics,Dates,Daily_Page_Visit_Count
0,.xxx_en.wikipedia.org_all-access_all-agents,2016-01-01,7089.0
1,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-01-01,6182.0
2,1._Juli_de.wikipedia.org_desktop_all-agents,2016-01-01,20.0
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-01-01,5363.0
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-01-01,3186.0

In [10]:
wiki_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549000 entries, 0 to 548999
Data columns (total 3 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Search_Topics           549000 non-null  object
 1   Dates                   549000 non-null  datetime64[ns]
 2   Daily_Page_Visit_Count  548913 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 12.6+ MB

In [12]:
wiki_2.dropna(inplace = True)
wiki_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 548913 entries, 0 to 548999
Data columns (total 3 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Search_Topics           548913 non-null  object
 1   Dates                   548913 non-null  datetime64[ns]
 2   Daily_Page_Visit_Count  548913 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 16.8+ MB

In [13]:
wiki_tidy = (wiki_2

 .assign(Month = lambda x: x['Dates']
        .dt.month_name())

.assign(Day = lambda x: x['Dates']
        .dt.day)       
)

wiki_tidy.head()

,Search_Topics,Dates,Daily_Page_Visit_Count,Month,Day
0,.xxx_en.wikipedia.org_all-access_all-agents,2016-01-01,7089.0,January,1
1,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-01-01,6182.0,January,1
2,1._Juli_de.wikipedia.org_desktop_all-agents,2016-01-01,20.0,January,1
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-01-01,5363.0,January,1
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-01-01,3186.0,January,1

In [14]:
wiki_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 548913 entries, 0 to 548999
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Search_Topics           548913 non-null  object
 1   Dates                   548913 non-null  datetime64[ns]
 2   Daily_Page_Visit_Count  548913 non-null  float64
 3   Month                   548913 non-null  object
 4   Day                     548913 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 25.1+ MB

SUBSETTING

In [16]:
Jan_wiki = wiki_tidy[wiki_tidy['Month'] == 'January']
Jan_wiki

,Search_Topics,Dates,Daily_Page_Visit_Count,Month,Day
0,.xxx_en.wikipedia.org_all-access_all-agents,2016-01-01,7089.0,January,1
1,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-01-01,6182.0,January,1
2,1._Juli_de.wikipedia.org_desktop_all-agents,2016-01-01,20.0,January,1
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-01-01,5363.0,January,1
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-01-01,3186.0,January,1
...,...,...,...,...,...
46495,Zac_Efron_en.wikipedia.org_all-access_all-agents,2016-01-31,17548.0,January,31
46496,Zayn_Malik_en.wikipedia.org_all-access_all-agents,2016-01-31,56947.0,January,31
46497,Zendaya_en.wikipedia.org_all-access_all-agents,2016-01-31,6298.0,January,31
46498,Zendaya_en.wikipedia.org_mobile-web_all-agents,2016-01-31,4021.0,January,31
46499,Zodiac_Killer_en.wikipedia.org_all-access_all-...,2016-01-31,8044.0,January,31

In [17]:
Jan_1 = (Jan_wiki[Jan_wiki['Day']==1])
Jan_1

,Search_Topics,Dates,Daily_Page_Visit_Count,Month,Day
0,.xxx_en.wikipedia.org_all-access_all-agents,2016-01-01,7089.0,January,1
1,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-01-01,6182.0,January,1
2,1._Juli_de.wikipedia.org_desktop_all-agents,2016-01-01,20.0,January,1
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-01-01,5363.0,January,1
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-01-01,3186.0,January,1
...,...,...,...,...,...
1495,Zac_Efron_en.wikipedia.org_all-access_all-agents,2016-01-01,14396.0,January,1
1496,Zayn_Malik_en.wikipedia.org_all-access_all-agents,2016-01-01,31663.0,January,1
1497,Zendaya_en.wikipedia.org_all-access_all-agents,2016-01-01,7091.0,January,1
1498,Zendaya_en.wikipedia.org_mobile-web_all-agents,2016-01-01,5221.0,January,1
1499,Zodiac_Killer_en.wikipedia.org_all-access_all-...,2016-01-01,4251.0,January,1

In [28]:
Jan = pd.DataFrame(Jan_1.groupby(["Daily_Page_Visit_Count"])["Search_Topics"])
Jan

               0                                                  1
0            5.0  38    ã‚¬ãƒ¼ã‚¼ã‚ªãƒ¼ãƒž_ja.wikipedia.org_all-...
1            7.0  467    è…”å®¤ç—‡å€™ç¾¤_zh.wikipedia.org_deskto...
2           10.0  621    Guns_N'_Roses_es.wikipedia.org_all-acce...
3           11.0  46    å¤§è¥¿è‹±ç”·_ja.wikipedia.org_desktop_al...
4           12.0  466    è…”å®¤ç—‡å€™ç¾¤_zh.wikipedia.org_all-ac...
...          ...                                                ...
1445   2306896.0  1463    Wikipedia:Hauptseite_de.wikipedia.org_...
1446   3062989.0  1461    Wikipedia:Hauptseite_de.wikipedia.org_...
1447   6920930.0  915    Main_Page_en.wikipedia.org_mobile-web_a...
1448   9170612.0  914    Main_Page_en.wikipedia.org_desktop_all-...
1449  16357307.0  912    Main_Page_en.wikipedia.org_all-access_a...

[1450 rows x 2 columns]

In [30]:
df_Jan1 = (Jan.rename(columns = {0: "Daily_Page_Visit_Count", 1: 'Search_Topics'}))
df_Jan1

,Daily_Page_Visit_Count,Search_Topics
0,5.0,38 ã‚¬ãƒ¼ã‚¼ã‚ªãƒ¼ãƒž_ja.wikipedia.org_all-...
1,7.0,467 è…”å®¤ç—‡å€™ç¾¤_zh.wikipedia.org_deskto...
2,10.0,621 Guns_N'_Roses_es.wikipedia.org_all-acce...
3,11.0,46 å¤§è¥¿è‹±ç”·_ja.wikipedia.org_desktop_al...
4,12.0,466 è…”å®¤ç—‡å€™ç¾¤_zh.wikipedia.org_all-ac...
...,...,...
1445,2306896.0,1463 Wikipedia:Hauptseite_de.wikipedia.org_...
1446,3062989.0,1461 Wikipedia:Hauptseite_de.wikipedia.org_...
1447,6920930.0,915 Main_Page_en.wikipedia.org_mobile-web_a...
1448,9170612.0,914 Main_Page_en.wikipedia.org_desktop_all-...
1449,16357307.0,912 Main_Page_en.wikipedia.org_all-access_a...

MOST TRENDING IN JANUARY

In [32]:
df_Jan1.tail(10)

,Daily_Page_Visit_Count,Search_Topics
1440,1214388.0,1464 Wikipedia:Portada_es.wikipedia.org_all...
1441,1253720.0,1449 WikipÃ©dia:Accueil_principal_fr.wikipe...
1442,1401667.0,1250 Special:Search_en.wikipedia.org_deskto...
1443,1532934.0,1447 WikipÃ©dia:Accueil_principal_fr.wikipe...
1444,1794204.0,1249 Special:Search_en.wikipedia.org_all-ac...
1445,2306896.0,1463 Wikipedia:Hauptseite_de.wikipedia.org_...
1446,3062989.0,1461 Wikipedia:Hauptseite_de.wikipedia.org_...
1447,6920930.0,915 Main_Page_en.wikipedia.org_mobile-web_a...
1448,9170612.0,914 Main_Page_en.wikipedia.org_desktop_all-...
1449,16357307.0,912 Main_Page_en.wikipedia.org_all-access_a...

MOST TRENDING FOR NOVEMBER 08

In [33]:
Nov_wiki = wiki_tidy[wiki_tidy['Month'] == 'November']
Nov_wiki

,Search_Topics,Dates,Daily_Page_Visit_Count,Month,Day
457500,.xxx_en.wikipedia.org_all-access_all-agents,2016-11-01,4788.0,November,1
457501,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-11-01,4210.0,November,1
457502,1._Juli_de.wikipedia.org_desktop_all-agents,2016-11-01,45.0,November,1
457503,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-11-01,3614.0,November,1
457504,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-11-01,1944.0,November,1
...,...,...,...,...,...
502495,Zac_Efron_en.wikipedia.org_all-access_all-agents,2016-11-30,8551.0,November,30
502496,Zayn_Malik_en.wikipedia.org_all-access_all-agents,2016-11-30,13840.0,November,30
502497,Zendaya_en.wikipedia.org_all-access_all-agents,2016-11-30,21273.0,November,30
502498,Zendaya_en.wikipedia.org_mobile-web_all-agents,2016-11-30,18220.0,November,30
502499,Zodiac_Killer_en.wikipedia.org_all-access_all-...,2016-11-30,8491.0,November,30

In [35]:
Nov_8 = (Nov_wiki[Nov_wiki['Day']==8])
Nov_8

,Search_Topics,Dates,Daily_Page_Visit_Count,Month,Day
468000,.xxx_en.wikipedia.org_all-access_all-agents,2016-11-08,3896.0,November,8
468001,.xxx_en.wikipedia.org_mobile-web_all-agents,2016-11-08,3415.0,November,8
468002,1._Juli_de.wikipedia.org_desktop_all-agents,2016-11-08,27.0,November,8
468003,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,2016-11-08,3703.0,November,8
468004,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,2016-11-08,2075.0,November,8
...,...,...,...,...,...
469495,Zac_Efron_en.wikipedia.org_all-access_all-agents,2016-11-08,8537.0,November,8
469496,Zayn_Malik_en.wikipedia.org_all-access_all-agents,2016-11-08,8403.0,November,8
469497,Zendaya_en.wikipedia.org_all-access_all-agents,2016-11-08,4602.0,November,8
469498,Zendaya_en.wikipedia.org_mobile-web_all-agents,2016-11-08,2892.0,November,8
469499,Zodiac_Killer_en.wikipedia.org_all-access_all-...,2016-11-08,10503.0,November,8

In [37]:
Nov = pd.DataFrame(Nov_8.groupby(["Daily_Page_Visit_Count"])["Search_Topics"])
Nov

               0                                                  1
0           10.0  468621    Guns_N'_Roses_es.wikipedia.org_all-a...
1           20.0  468046    å¤§è¥¿è‹±ç”·_ja.wikipedia.org_deskto...
2           26.0  468338    Copa_AmÃ©rica_2015_fr.wikipedia.org_...
3           27.0  468002    1._Juli_de.wikipedia.org_desktop_all...
4           33.0  468467    è…”å®¤ç—‡å€™ç¾¤_zh.wikipedia.org_des...
...          ...                                                ...
1438   2246978.0  469249    Special:Search_en.wikipedia.org_all-...
1439   2829085.0  469461    Wikipedia:Hauptseite_de.wikipedia.or...
1440   4161059.0  468915    Main_Page_en.wikipedia.org_mobile-we...
1441  20367321.0  468914    Main_Page_en.wikipedia.org_desktop_a...
1442  24600978.0  468912    Main_Page_en.wikipedia.org_all-acces...

[1443 rows x 2 columns]

In [38]:
df_Nov8 = (Nov.rename(columns = {0: "Daily_Page_Visit_Count", 1: 'Search_Topics'}))
df_Nov8

,Daily_Page_Visit_Count,Search_Topics
0,10.0,468621 Guns_N'_Roses_es.wikipedia.org_all-a...
1,20.0,468046 å¤§è¥¿è‹±ç”·_ja.wikipedia.org_deskto...
2,26.0,468338 Copa_AmÃ©rica_2015_fr.wikipedia.org_...
3,27.0,468002 1._Juli_de.wikipedia.org_desktop_all...
4,33.0,468467 è…”å®¤ç—‡å€™ç¾¤_zh.wikipedia.org_des...
...,...,...
1438,2246978.0,469249 Special:Search_en.wikipedia.org_all-...
1439,2829085.0,469461 Wikipedia:Hauptseite_de.wikipedia.or...
1440,4161059.0,468915 Main_Page_en.wikipedia.org_mobile-we...
1441,20367321.0,468914 Main_Page_en.wikipedia.org_desktop_a...
1442,24600978.0,468912 Main_Page_en.wikipedia.org_all-acces...

In [39]:
df_Nov8.tail(10)

,Daily_Page_Visit_Count,Search_Topics
1433,1182277.0,469464 Wikipedia:Portada_es.wikipedia.org_a...
1434,1379041.0,468408 Ð—Ð°Ð³Ð»Ð°Ð²Ð½Ð°Ñ_ÑÑ‚Ñ€Ð°Ð½Ð¸Ñ†Ð°_...
1435,1464684.0,469447 WikipÃ©dia:Accueil_principal_fr.wiki...
1436,1796203.0,469250 Special:Search_en.wikipedia.org_desk...
1437,1796959.0,469463 Wikipedia:Hauptseite_de.wikipedia.or...
1438,2246978.0,469249 Special:Search_en.wikipedia.org_all-...
1439,2829085.0,469461 Wikipedia:Hauptseite_de.wikipedia.or...
1440,4161059.0,468915 Main_Page_en.wikipedia.org_mobile-we...
1441,20367321.0,468914 Main_Page_en.wikipedia.org_desktop_a...
1442,24600978.0,468912 Main_Page_en.wikipedia.org_all-acces...